<?php include('head.html'); ?>


<section>
<article>
<h1>Terminos &amp; condiciones</h1>
<br />
<p>CONDICIONES DE USO <br>
SÍRVASE LEER LAS SIGUIENTES CONDICIONES DE USO  CUIDADOSAMENTE ANTES  DE UTILIZAR ESTE  SITIO. AL USAR ESTE SITIO USTED ACEPTA FORMALMENTE  TODAS LAS CONDICIONES AQUÍ DESCRITAS. LA  EMPRESA SE RESERVA EL DERECHO  BAJO  PROPIO CRITERIO DE ACTUALIZAR LAS MISMAS CUANDO ASÍ LO CONSIDERE  NECESARIO. <br>
POR FAVOR, REVÍSELAS PERIÓDICAMENTE PARA ESTAR  INFORMADO DE LOS CAMBIOS. </p>
<p>
  1. Condiciones Generales. Este sitio web es propiedad  de Lu’um balam S.A. de C.V., quien se reserva el derecho de modificar en  cualquier momento cualquier aspecto o característica de este sitio web,  incluyendo sin limitación alguna, la información, horas de disponibilidad y  equipo necesario para el acceso y uso del mismo. </p>
<p>
  2. Uso de cookies. Nuestro sitio usa cookies para  mantener el control en  su recorrido y  datos relacionados. Estas cookies expiran cuando usted cierra su explorador. </p>
<p>
  3. Sitios de Vínculos y Terceras Partes. Este sitio  puede vincularlo con otros sitios de Internet. Estos sitios no están  controladas por Lu’um Balam por lo que hacemos de su conocimiento que  luumbalam.com no se hace responsable por ninguno de los contenidos de estos  sitios. La inclusión de este vínculo no implica un respaldo de luumbalam.com ni  una asociación con estos operadores. Adicionalmente luumbalam.com no es responsable  por las prácticas de privacidad de dichos sitios. </p>
<p>
  4. Seguridad. luumbalam.com está obligada a cumplir  con toda la normativa aplicable en materia de medidas de seguridad relacionadas  a su información personal. Adicionalmente, luumbalam.com usa los estándares de  la industria en materia de protección de la confidencialidad de su información  personal, incluyendo en otras medidas Secure Socket Layers  (&quot;SSL&quot;).  luumbalam.com  considera sus datos como un activo que debe ser protegido de cualquier pérdida  o acceso no autorizado. Empleamos diversas técnicas de seguridad para  protegerle de accesos por usuarios no autorizados. </p>
<p>
  5. Restricciones de Uso. </p>
<p>
  A. El usuario no deberá anunciar o transmitir a  través de este sitio web ningún material que viole o infrinja en modo alguno  los derechos de otros, que sea ilegal, amenazante, abusivo, difamatorio,  invasivo de los derechos de privacidad o de publicidad, grosero, obsceno,  profano de otro modo censurable, que aliente conductas que constituyan un  delito, cree alguna responsabilidad civil o que de otra manera viole cualquier  ley. El usuario no deberá anunciar o transmitir a través de este sitio web  ningún material que contenga anuncios u ofertas con respecto a productos o  servicios, sin la expresa autorización previa y por escrito de  Lu’um Balam, S.A. de C.V. El usuario no  deberá usar este sitio web para anunciar o hacer ninguna oferta comercial,  incluyendo, sin limitación alguna, pedidos para que los usuarios se suscriban a  otros servicios de información en línea (&quot;on-line&quot;) competitivos con  este sitio web. Cualquier acción realizada por el usuario que a criterio  de  Lu’um Balam, S.A. de C.V. restrinja o  prohíba a otro usuario usar o disfrutar este sitio web no será permitida. </p>
<p>
  B. Este sitio web contiene material protegido por  derechos de autor, marcas registradas y otros derechos comerciales, incluyendo  sin limitación alguna, textos, software, fotografías, videos, gráficos, música  y sonidos. El contenido de este sitio web está protegido por las leyes de  derechos de autor de los Estados Unidos Mexicanos. El usuario no podrá  modificar, publicar, transmitir, mostrar, participar en la transferencia o en  la venta, crear obras derivadas o en forma alguna explotar el contenido total o  parcial de este sitio web. El usuario sólo podrá hacer una sola copia del  material protegido por derechos de autor de este sitio web siempre y cuando sea  exclusivamente para uso personal, no comercial y en su domicilio. Excepto por  lo que esté expresamente permitido conforme las leyes de derecho de autor,  copiar, redistribuir, retransmitir, publicar o comercializar cualquier material  obtenido (&quot;downloaded&quot;) de este sitio web está prohibido y no será  permitido sin el consentimiento expreso, previo y por escrito de Lu’um Balam,  S.A. de C.V. En el caso de que se autorice el copiado, redistribución o  publicación de algún material protegido por derechos de autor del sitio web, no  deberá cambiarse o eliminarse el reconocimiento al autor, las leyendas de  marcas comerciales o las leyendas de derechos de autor. El usuario reconoce que  al obtener (&quot;download&quot;) material protegido por derechos de autor del  sitio web, no adquiere ningún derecho de propiedad sobre éste. </p>
 
<p>C. El usuario no deberá insertar  (&quot;upload&quot;), presentar o de cualquier otra forma hacer que esté  disponible en el sitio web ningún material protegido por derechos de autor,  marca comercial u otro derecho de propiedad sin el consentimiento expreso del  propietario de los derechos de autor, marca comercial u otro derecho de  propiedad, siendo que la responsabilidad de determinar si el material no está  protegido por derechos de autor será exclusivamente del usuario. El usuario  será responsable en forma exclusiva por todos los daños y perjuicios causados  por una violación de los derechos de autor, derechos de propiedad o por  cualquier otro daño causado por dicha presentación. Al presentar material en  cualquier área de acceso público en el sitio web, el usuario automáticamente  otorga o garantiza que el propietario de dicho material ha otorgado expresamente  a Lu’um Balam, S.A. de C.V., libre de toda regalía y de forma universal,  perpetua e irrevocable, el derecho y la licencia, no exclusiva, de usar,  reproducir, modificar, adaptar, publicar, mostrar, traducir y de distribuir  dicho material total o parcialmente o de incorporarlo en otra obra, medio o  tecnología presente y futura. El usuario permitirá igualmente a cualquier otro  usuario del sitio web, acceso al material así como autorización para observar,  guardar o reproducir el material para su uso personal. El usuario otorga  igualmente a Lu’um Balam, S.A. de C.V. el derecho de editar, copiar, mostrar,  publicar y distribuir todo material que él haga disponible en el sitio web. </p>
<p>
  D. Las disposiciones anteriormente estipuladas en  esta Sección 5 han sido incluidas y deberán ser interpretadas en beneficio de Lu’um  Balam, S.A. de C.V., sus subsidiarias, afiliados y proveedores de contenido  independientes, así como cedentes y cada uno de estos tendrá derecho de afirmar  y hacer valer estas disposiciones directamente por su propio beneficio. </p>
<p>E. Limitation of Liability. El usuario acepta  explícitamente que el uso de este sitio web será exclusivamente bajo su riesgo.  Ni  Lu’um Balam, S.A. de C.V. ni sus  afiliados, empleados, agentes, proveedores de contenido o cedentes, garantizan  que este sitio web no será interrumpido o que está libre de errores; tampoco  garantizan los resultados que se puedan obtener por el uso de este sitio web o  fiabilidad de la información, servicios previstos a través de este. <br>
  Este sitio web se ofrece &quot;como está&quot; sin  garantía de ningún tipo, ni expresa, ni implícitamente, incluyendo sin  limitación alguna , las garantías de título o garantías implícitas de  comerciabilidad o aptitud para un propósito particular, excepto las garantías  implícitas bajo las leyes vigentes y por tanto no sujetas a exclusión,  restricción o modificación. Adicionalmente, no hay garantías con respecto a los  resultados que se obtengan por el uso del sitio web. <br>
  El usuario reconoce que las disposiciones de esta  sección se aplicarán al uso y contenido de este sitio web. La ley aplicable  puede no permitir la limitación o la exclusión de responsabilidad, o daños y  perjuicios incidentales o consecuenciales, y por consiguiente, la limitación  especificada anteriormente puede no aplicarse a determinado usuario. De ninguna  manera, la totalidad de la responsabilidad de   Lu’um Balam, S.A. de C.V. hacia el usuario por cualquier daño o  perjuicio, pérdida, derecho de acción, sea por contrato o por cuasidelito  (incluyendo su propia negligencia) o bajo cualquier otra teoría legal  (incluyendo responsabilidad absoluta), excederá la cantidad pagada por el  usuario, si hubiera alguna, por obtener acceso a este sitio web. </p>
<p>
  F. Monitoreo. Lu’um Balam, S.A. de C.V. se reserva  el derecho, pero no estará obligado, a monitorear el contenido del sitio web  para determinar el cumplimiento con estas condiciones de uso y cualquier otro  reglamento de uso u operación establecido por Lu’um Balam, S.A. de C.V. para  cumplir con cualquier ley, reglamento o requerimiento del gobierno. Lu’um Balam,  S.A. de C.V. se reserva el derecho, según su criterio, de editar, rehusar  anuncios o suprimir cualquier material incluido o anunciado en el sitio web.  Sin que esto constituya una limitación a Lu’um Balam, S.A. de C.V. tendrá  derecho a suprimir cualquier material que a su absoluto criterio considere que  viola las disposiciones aquí mencionadas o de alguna manera censurables. </p>
<p>
  G. Indemnización. El usuario se compromete a  defender, indemnizar y amparar  Lu’um Balam,  S.A. de C.V. y sus afiliados y sus respectivos agentes, directores, oficiales,  empleados y agentes ante cualquier reclamo, acción, demanda, daño, perjuicio,  costos, responsabilidades, pérdidas y gastos (incluyendo honorarios razonables  de abogados) que puedan resultar del uso de este sitio web. </p>
<p>
  H. Marcas Comerciales. El nombre  Lu’um Balam, S.A. de C.V.&quot; así como cada  uno de sus logos, son marcas comerciales con todos los derechos reservados.  Todas las otras marcas comerciales que aparecen en el sitio web son de su  propiedad o cuenta con licencia para su uso. </p>
<p>
  I. Cambio de Términos. Lu’um Balam, S.A. de C.V. se  reserva el derecho, en cualquier momento, de cambiar o modificar los términos y  condiciones aplicables al uso de este sitio web, o de cualquier parte de éste,  o de imponer nuevas condiciones. </p>
<p>
  6. Varios. Estos términos de uso constituyen el  acuerdo íntegro entre las partes con respecto a los asuntos tratados en el  presente y remplazan todos los acuerdos previos, escritos u orales, entre las  partes con respecto a lo tratado. Ninguna renuncia al reclamo por una violación  o incumplimiento de lo dispuesto en el presente deberá considerarse como una  renuncia a reclamar cualquier violación o incumplimiento previo o subsecuente.  Los títulos de las secciones usados en el presente son solamente referenciales  y no se deberá otorgar a éstos efecto legal alguno. </p>
<p>
  Derechos Reservados © 2012  Lu’um Balam, S.A. de C.V. </p>

</article>
<?php include('aside.html'); ?>
</section>

<?php include('footer.html'); ?>